AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
  TargetRubyVersion: 2.3

Style/Encoding:
  Enabled: true

Style/AccessorMethodName:
  Enabled: false

Style/PredicateName:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/LineLength:
  Max: 99

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

Documentation:
  Enabled: false

Rails:
  Enabled: true
